# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate column means of a NumericMatrix
#' @param x predictors matrix
#' @return mean of x
colMeansRcpp <- function(x) {
    .Call(`_mlrmodel_colMeansRcpp`, x)
}

